This project contains code for fitting 2D maps generated by SLAM algorithms to the ground truth map. More generally it can be used to fit any map to another version of it that has been translated and/or rotated. Here we do not account for reflections because we consider a reflected map to be a different floorplan.


### Interface

There are 3 main inputs that are needed to run the code. One is the image of the ground truth file, another is a json file with the corners of the ground truth (you can find example of such a file in data/ground_truth.json) and the last one is the image of the map to be fitted to the ground truth.

If you have these three you can invoke the code by running:

python fit_map.py from_gt_img_and_corners_file gt_corners

```
fit_map.py from_gt_img_and_corners_file ../data/ground_truth.json ../data/ground_truth.png floorplan.pgm --show
```

### Data

### Approach

The approach is described in the pages blog post: link

### Examples

Here are some successful examples of fitting.

